name: バグ報告
description: 問題の報告をして、改善に役立てます
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: 問題の内容
      description: 何が起きましたか？再現手順や期待する動作を含めて自由に記入してください。
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: スクリーンショット（任意）
      description: 問題がわかる画像があれば添付してください。
