name: ドキュメント修正
description: ドキュメントの改善や追加
title: "[DOCS] "
labels: ["documentation"]
body:
  - type: textarea
    id: summary
    attributes:
      label: 修正の内容
      description: どのドキュメントをどのように、なぜ修正するか記入してください。
    validations:
      required: true
