name: 機能リクエスト
description: 新しい機能の提案
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: 機能の概要
      description: 追加したい機能の内容や、解決したい課題を自由に記入してください。
    validations:
      required: true
